// =====================================================
// LEON.CS - C# missions aggregator
//
// TIPOS DE STEP:
//   type:"mc"   -- multipla escolha (4 opcoes)
//   type:"code" -- leia o codigo + multipla escolha
//   type:"fill" -- complete o codigo (digitacao livre)
//
// CORES DO CODIGO (use <span class="CLASSE">):
//   kw  roxo    -- int, void, if, for, class, using
//   tp  azul    -- string, List, bool, double
//   st  rosa    -- "strings entre aspas"
//   cm  cinza   -- // comentarios
//   nm  amarelo -- numeros: 42, 3.14
//   mt  ciano   -- metodos: WriteLine, Add, Remove
// =====================================================

const MISSIONS = [
  MISSION_0,
  MISSION_01,
  MISSION_02,
  MISSION_03,
  MISSION_04,
  MISSION_05,
  MISSION_06,
  MISSION_07,
  MISSION_08,
  MISSION_09,
  MISSION_10,
  MISSION_11,
  MISSION_12,
  MISSION_13,
  MISSION_14,
  MISSION_15,
  MISSION_16,
  MISSION_17,
  MISSION_18,
  MISSION_19,
  MISSION_20,
  MISSION_21,
  MISSION_22,
  MISSION_23,
  MISSION_24,
  MISSION_25,
  MISSION_26,
  MISSION_27,
  MISSION_28,
  MISSION_29,
  MISSION_30,
  MISSION_31,
  MISSION_32,
  MISSION_33,
  MISSION_34,
  MISSION_35,
  MISSION_36,
  MISSION_37,
  MISSION_38,
  MISSION_39,
  MISSION_40,
  MISSION_41,
  MISSION_42,
  MISSION_43,
  MISSION_44,
  MISSION_45,
  MISSION_46,
  MISSION_47,
  MISSION_48,
  MISSION_49,
  MISSION_50,
  MISSION_51,
  MISSION_52,
  MISSION_53,
  MISSION_54,
  MISSION_55,
  MISSION_56,
  MISSION_57,
  MISSION_58,
  MISSION_59,
  MISSION_60,
  MISSION_61,
  MISSION_62,
  MISSION_63,
  MISSION_64,
  MISSION_65,
  MISSION_66,
  MISSION_67,
  MISSION_68,
  MISSION_69,
  MISSION_70,
  MISSION_71,
  MISSION_72,
  MISSION_73,
  MISSION_74,
  MISSION_75,
  MISSION_76,
  MISSION_77,
  MISSION_78,
  MISSION_79,
  MISSION_80,
  MISSION_81,
  MISSION_82,
  MISSION_83,
  MISSION_84,
  MISSION_85,
  MISSION_86,
  MISSION_87,
  MISSION_88,
  MISSION_89,
  MISSION_90,
  MISSION_91,
  MISSION_92,
  MISSION_93,
  MISSION_94,
  MISSION_95,
  MISSION_96,
  MISSION_97,
  MISSION_98,
  MISSION_99,
];
